### ISSUE TITLE
No easy way to run all the tests 

### ISSUE THREAD

**Issue by amuradyan** [Chalyan/SICP#10]
Currently, we have to go to each folder to run the corresponding tests. This can be automated via makefiles /see [make](https://man7.org/linux/man-pages/man1/make.1.html)/.

**Comment by Chalyan** [comment]
The problem is solved. Please, review the changes :)

**Comment by amuradyan** [comment]
A solution was proposed in #9, but it still needs to be shaped, since the amount of mechanical work is too much.
